### ISSUE TITLE
Expose USB devices to Home Assistant

### ISSUE THREAD

**Issue by sunsided** [sunsided/epimelitis#1]
- [x] Get Zigbee USB stick to work on Raspberry Pi
- [x] Pass USB device through to Qemu / libvirt
- [x] Pass USB device through to Talos
- [x] Pass USB device through to Home Assistant Container
- [ ] Label the Node with Zigbee and add a node selector the Home Assistant Pod

## Notes to self

 ```yaml
  volumes:
  - name: usb
    hostPath:
      path: /dev/bus/usb
```
